development: &dev
  secret_key_base: /home/heckfyxe/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/pry-byebug-3.8.0/lib/pry-byebug/control_d_handler.rb:5: warning: control_d_handler's arity of 2 parameters was deprecated (eval_string, pry_instance). Now it gets passed just 1 parameter (pry_instance)
82591390400f1d6b0a89f2461257ada9a60b3af34bac1d97022528d921fc3c2edfadc0709ccb9c1dd8f76e0d188b615bc6d27e0135ab48bf9330dea7f971cb17

  telegram:
    bot:
      token: BOT_TOKEN
      username: BOT_NAME
      # async: true
      # botan:
      #   token: botan_token
      #   # async: true

test:
  secret_key_base: /home/heckfyxe/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/pry-byebug-3.8.0/lib/pry-byebug/control_d_handler.rb:5: warning: control_d_handler's arity of 2 parameters was deprecated (eval_string, pry_instance). Now it gets passed just 1 parameter (pry_instance)
cdb279531105f52d48c476f07259382c6b12f3190220135f7fd4caa36a3336d1f73cd5b7a1b1596cc85e7449e0a07753e7dad9c7200349b331cdf2b5d743e4d7

  telegram:
    bot:
      token: test_bot_token
      username: BOT_NAME

production:
  <<: *dev
